package org.maharshak.teg.common;

public enum TEG_STATUS {
	TEG_STATUS_SUCCESS,
	TEG_STATUS_ERROR,
	TEG_STATUS_NOTFOUND,
	TEG_STATUS_NOMEM,
	TEG_STATUS_CONNCLOSED ,
	TEG_STATUS_TOKENNOTFOUND ,
	TEG_STATUS_TOKENNULL ,
	TEG_STATUS_PLAYERNOTFOUND ,
	TEG_STATUS_PARSEERROR ,
	TEG_STATUS_NOTCONNECTED ,
	TEG_STATUS_UNEXPECTED ,
	TEG_STATUS_FILENOTFOUND ,
	TEG_STATUS_GAMEOVER ,
	TEG_STATUS_THEMEERROR ,
}
