package org.maharshak.teg.game.event;

public enum EventType {
  COLOUR_SET, PLAYER_ADDED, MISSION_SET, GAME_STATE_CHANGED, EXCHANGE, GOT_CARD, USED_CARD_FOR_ARMY, MOVE_TROOPS, MESSAGE, LOST_GAME, WON_GAME, ATTACK_FINISHED, ATTACK_STARTED, NEW_ROUND, DISMISS_PLAYER, PLAYER_STATE_CHANGED, DEFINITION_LOCKED;
}
